# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b41db480245e2d87724e07fb83122aaf6a6cd204d736be50eb4c2afc745d6152dd5be581f75f0c98cb6f28fdb1a890f617829646a2c628367899dea9dce123d

test:
  secret_key_base: 75f12387fec4c5c4c2ec4184fec5c9b9dd2d99dcb58dec99b6ca336d48dc6e8d7894c180566fd34eae1908fea1c457cfbabb97e6c8bbf1fd9fcc9c0909e10a81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
